variables:
  CI_DISPOSABLE_ENVIRONMENT: "true"
  CLOUD_SDK_VERSION: "218.0.0"
  DOCKER_DRIVER: overlay2

image: blockstream/gcloud-docker@sha256:2e20abd14c17685224e8504a4cc4121f6189bee1b7dae14c267af3ee8b712bd7
stages:
  - build
  - plan
  - deploy

before_script:
  - TMPF=$(mktemp) || exit 1
  - echo $GCLOUD_KEY > $TMPF
  - export GOOGLE_APPLICATION_CREDENTIALS=$TMPF
  - gcloud auth activate-service-account --key-file=$TMPF
  - gcloud auth list
  - gcloud --version
  - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin

test_docker_build_image:
  except:
    - schedules
  image: docker@sha256:f7211e1779c82e3a50d0d6f165e83f3e2be217a234b0181d5e8bee411d8fcc5f
  stage: build
  before_script:
    - echo "Disabling before script"
  except:
    - tags
    - master
  script:
    - docker pull blockstream/esplora-base:latest
    - docker pull blockstream/esplora:latest
    - docker build
        --cache-from blockstream/esplora-base:latest
        -f Dockerfile.deps
        -t esplora-base .
    - docker build
        --squash
        --build-arg FOOT_HTML='<!-- '"$CI_COMMIT_SHA"'-->'
        --cache-from blockstream/esplora:latest
        -t esplora .
    - docker rmi esplora-base || true
    - docker rmi esplora || true

build:
  stage: build
  only:
    - /^bitcoin_mainnet.*/
    - /^bitcoin_testnet.*/
    - /^liquid_mainnet.*/
    - master@greenaddress/esplora
  script:
    - docker pull debian:stretch || true
    - docker pull blockstream/esplora-base:latest || true
    - docker build --cache-from blockstream/esplora-base:latest -t blockstream/esplora-base:$CI_COMMIT_REF_SLUG -t blockstream/esplora-base:latest -f Dockerfile.deps .
    - docker push blockstream/esplora-base:latest
    - esplora_base_sha=$(docker inspect --format='{{index .RepoDigests 0}}' blockstream/esplora-base:$CI_COMMIT_REF_SLUG)
    - sed -i "s~blockstream/esplora-base:latest~${esplora_base_sha}~g" Dockerfile
    - curl "https://hub.docker.com/v2/repositories/blockstream/esplora/tags/" | grep -q "$CI_COMMIT_SHA" || (
        docker pull blockstream/esplora:latest
        && docker build
          --build-arg FOOT_HTML='<!-- '"$CI_COMMIT_SHA"' -->'
          --cache-from blockstream/esplora:latest
          -t blockstream/esplora:latest .
        && docker push blockstream/esplora:latest
        && docker build
          --squash
          --build-arg FOOT_HTML='<!-- '"$CI_COMMIT_SHA"' -->'
          --cache-from blockstream/esplora:latest
          -t blockstream/esplora:$CI_COMMIT_SHA .
        && docker push blockstream/esplora:$CI_COMMIT_SHA)

plan:
  except:
    - /^bitcoin_mainnet.*/
    - /^bitcoin_testnet.*/
    - /^liquid_mainnet.*/
    - master@greenaddress/esplora
    - schedules
  only:
    - branches@greenaddress/esplora
  stage: plan
  image:
    name: blockstream/gcloud-docker@sha256:2e20abd14c17685224e8504a4cc4121f6189bee1b7dae14c267af3ee8b712bd7
    entrypoint: [""]
  script:
    - (echo -n "$V2_PK" > terraform/modules/tor/v2.pk)
    - (echo -n "$V3_PK" > terraform/modules/tor/v3.pk)
    - (echo -n "$V3_PUBK" > terraform/modules/tor/v3.pubk)
    - (cd terraform && terraform init -input=false &&
       terraform workspace select main &&
       terraform plan
        -var "prometheus_allowed_source_ip=$PROMETHEUS_ALLOWED_SOURCE_IP"
        -var "hosts=$HOSTS"
        -var "hosts_onion=$HOSTS_ONION"
        -var "cluster_size=$NODE_CLUSTER_SIZE"
        -var "instance_type=$NODE_INSTANCE_TYPE"
        -var "regions=$REGIONS"
        -var "zones=$ZONES"
        -var "ssl_certs=$SSL_CERTS"
        -var "opsgenie_api_key=$OPSGENIE_API_KEY"
        -var "image_source_project=$IMAGE_SOURCE_PROJECT"
        -input=false)

deploy_main:
  except:
    - schedules
  stage: deploy
  image:
    name: blockstream/gcloud-docker@sha256:2e20abd14c17685224e8504a4cc4121f6189bee1b7dae14c267af3ee8b712bd7
    entrypoint: [""]
  only:
    - /^main_v.*/
  script:
    - (echo -n "$V2_PK" > terraform/modules/tor/v2.pk)
    - (echo -n "$V3_PK" > terraform/modules/tor/v3.pk)
    - (echo -n "$V3_PUBK" > terraform/modules/tor/v3.pubk)
    - (cd terraform && terraform init -input=false &&
       terraform workspace select main &&
       terraform apply
        -var "prometheus_allowed_source_ip=$PROMETHEUS_ALLOWED_SOURCE_IP"
        -var "hosts=$HOSTS"
        -var "hosts_onion=$HOSTS_ONION"
        -var "cluster_size=$NODE_CLUSTER_SIZE"
        -var "instance_type=$NODE_INSTANCE_TYPE"
        -var "regions=$REGIONS"
        -var "zones=$ZONES"
        -var "ssl_certs=$SSL_CERTS"
        -var "opsgenie_api_key=$OPSGENIE_API_KEY"
        -var "image_source_project=$IMAGE_SOURCE_PROJECT"
        -input=false -auto-approve)

deploy_bitcoin_mainnet:
  except:
    - schedules
  stage: deploy
  image:
    name: blockstream/gcloud-docker@sha256:2e20abd14c17685224e8504a4cc4121f6189bee1b7dae14c267af3ee8b712bd7
    entrypoint: [""]
  only:
    - /^bitcoin_mainnet.*/
  script:
    - (cd terraform && terraform init -input=false &&
       terraform workspace select bitcoin-mainnet &&
       terraform apply
        -var "docker_tag_explorer=blockstream/esplora:$CI_COMMIT_SHA"
        -var "cluster_size=$NODE_CLUSTER_SIZE"
        -var "instance_type=$NODE_INSTANCE_TYPE"
        -var "regions=$REGIONS"
        -var "zones=$ZONES"
        -var "min_ready_sec=300"
        -var "initial_delay_sec=2400"
        -var "image_source_project=$IMAGE_SOURCE_PROJECT"
        -input=false -auto-approve)

deploy_bitcoin_testnet:
  except:
    - schedules
  stage: deploy
  image:
    name: blockstream/gcloud-docker@sha256:2e20abd14c17685224e8504a4cc4121f6189bee1b7dae14c267af3ee8b712bd7
    entrypoint: [""]
  only:
    - /^bitcoin_testnet.*/
  script:
    - (cd terraform && terraform init -input=false &&
       terraform workspace select bitcoin-testnet &&
       terraform apply
        -var "docker_tag_explorer=blockstream/esplora:$CI_COMMIT_SHA"
        -var "cluster_size=$NODE_CLUSTER_SIZE"
        -var "instance_type=$NODE_INSTANCE_TYPE"
        -var "regions=$REGIONS"
        -var "zones=$ZONES"
        -var "min_ready_sec=60"
        -var "initial_delay_sec=600"
        -var "image_source_project=$IMAGE_SOURCE_PROJECT"
        -input=false -auto-approve)

deploy_liquid_mainnet:
  except:
    - schedules
  stage: deploy
  image:
    name: blockstream/gcloud-docker@sha256:2e20abd14c17685224e8504a4cc4121f6189bee1b7dae14c267af3ee8b712bd7
    entrypoint: [""]
  only:
    - /^liquid_mainnet.*/
  script:
    - (cd terraform && terraform init -input=false &&
       terraform workspace select liquid-mainnet &&
       terraform apply
        -var "docker_tag_explorer=blockstream/esplora:$CI_COMMIT_SHA"
        -var "cluster_size=$NODE_CLUSTER_SIZE"
        -var "instance_type=$NODE_INSTANCE_TYPE"
        -var "regions=$REGIONS"
        -var "zones=$ZONES"
        -var "min_ready_sec=120"
        -var "initial_delay_sec=1200"
        -var "image_source_project=$IMAGE_SOURCE_PROJECT"
        -input=false -auto-approve)
