deploy_staging_bitcoin_mainnet:
  extends: .k8s_setup
  only:
    - /^staging_bitcoin_mainnet.*/
  variables:
    KUBE_SERVER_US: $GKE_STAGING_SERVER_US
    KUBE_TOKEN_US: $GKE_STAGING_TOKEN_US
    KUBE_NAMESPACE: $GKE_STAGING_NAMESPACE
    KUBE_WORKLOAD: $GKE_STAGING_WORKLOAD_BTCM
    KUBE_CONTAINER: $GKE_STAGING_CONTAINER

deploy_staging_bitcoin_testnet:
  extends: .k8s_setup
  only:
    - /^staging_bitcoin_testnet.*/
  variables:
    KUBE_SERVER_US: $GKE_STAGING_SERVER_US
    KUBE_TOKEN_US: $GKE_STAGING_TOKEN_US
    KUBE_NAMESPACE: $GKE_STAGING_NAMESPACE
    KUBE_WORKLOAD: $GKE_STAGING_WORKLOAD_BTCT
    KUBE_CONTAINER: $GKE_STAGING_CONTAINER

deploy_staging_liquid_mainnet:
  extends: .k8s_setup
  only:
    - /^staging_liquid_mainnet.*/
  variables:
    KUBE_SERVER_US: $GKE_STAGING_SERVER_US
    KUBE_TOKEN_US: $GKE_STAGING_TOKEN_US
    KUBE_NAMESPACE: $GKE_STAGING_NAMESPACE
    KUBE_WORKLOAD: $GKE_STAGING_WORKLOAD_LIQM
    KUBE_CONTAINER: $GKE_STAGING_CONTAINER

deploy_staging_liquid_testnet:
  extends: .k8s_setup
  only:
    - /^staging_liquid_testnet.*/
  variables:
    KUBE_SERVER_US: $GKE_STAGING_SERVER_US
    KUBE_TOKEN_US: $GKE_STAGING_TOKEN_US
    KUBE_NAMESPACE: $GKE_STAGING_NAMESPACE
    KUBE_WORKLOAD: $GKE_STAGING_WORKLOAD_LIQT
    KUBE_CONTAINER: $GKE_STAGING_CONTAINER
